"""
models.py — SQLAlchemy ORM table definitions
Tables: users, vehicles, family_members, parking_sessions, parking_counter
"""
from sqlalchemy import (
    Column, Integer, String, Boolean, BigInteger, ForeignKey
)
from sqlalchemy.orm import relationship
from database import Base


# ─────────────────────────────────────────────────────────────────────────────
# User
# ─────────────────────────────────────────────────────────────────────────────
class User(Base):
    __tablename__ = "users"

    id              = Column(Integer, primary_key=True, index=True)
    name            = Column(String,  nullable=False)
    email           = Column(String,  unique=True, index=True, nullable=False)
    password        = Column(String,  nullable=False)              # bcrypt hash
    tier            = Column(String,  default="free")              # free | premium | family | admin
    premium_expiry  = Column(BigInteger, nullable=True)            # epoch ms; NULL = never set
    created_at      = Column(BigInteger, nullable=False)           # epoch ms

    vehicles        = relationship("Vehicle",       back_populates="owner",  cascade="all, delete-orphan")
    family_members  = relationship("FamilyMember",  back_populates="owner",  cascade="all, delete-orphan")
    parking_sessions= relationship("ParkingSession",back_populates="user",   cascade="all, delete-orphan")


# ─────────────────────────────────────────────────────────────────────────────
# Vehicle
# ─────────────────────────────────────────────────────────────────────────────
class Vehicle(Base):
    __tablename__ = "vehicles"

    id      = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    number  = Column(String,  nullable=False)        # e.g. MH12AB1234  (uppercase)
    type    = Column(String,  default="car")          # car | bike | truck
    name    = Column(String,  nullable=False)         # friendly name, e.g. "Honda City"

    owner   = relationship("User", back_populates="vehicles")


# ─────────────────────────────────────────────────────────────────────────────
# FamilyMember  (only active for users on the family plan)
# ─────────────────────────────────────────────────────────────────────────────
class FamilyMember(Base):
    __tablename__ = "family_members"

    id       = Column(Integer, primary_key=True, index=True)
    owner_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    name     = Column(String,  nullable=False)
    email    = Column(String,  nullable=False)

    owner    = relationship("User", back_populates="family_members")


# ─────────────────────────────────────────────────────────────────────────────
# ParkingSession
# ─────────────────────────────────────────────────────────────────────────────
class ParkingSession(Base):
    __tablename__ = "parking_sessions"

    # Primary key  —  PKG000001 format, generated by the counter table
    id              = Column(String,     primary_key=True, index=True)

    # Who parked
    user_id         = Column(Integer,    ForeignKey("users.id"), nullable=False)
    user_email      = Column(String,     nullable=False)
    user_name       = Column(String,     nullable=False)
    user_tier       = Column(String,     default="free")        # snapshot of tier at time of parking

    # Vehicle snapshot (stored flat so records survive vehicle deletion)
    vehicle_id      = Column(Integer,    ForeignKey("vehicles.id"), nullable=True)
    vehicle_number  = Column(String,     nullable=False)
    vehicle_name    = Column(String,     nullable=False)
    vehicle_type    = Column(String,     nullable=False)

    # Location
    state           = Column(String,     nullable=False)
    city            = Column(String,     nullable=False)
    facility        = Column(String,     nullable=False)
    area            = Column(String,     nullable=False)
    slot            = Column(Integer,    nullable=False)
    entry           = Column(String,     nullable=False)

    # Timing  (epoch milliseconds, same format as frontend)
    start_time      = Column(BigInteger, nullable=False)
    end_time        = Column(BigInteger, nullable=True)          # NULL = still active

    # Fine
    fine            = Column(Integer,    default=0)              # ₹ amount
    fine_reason     = Column(String,     default="")
    fine_paid       = Column(Boolean,    default=False)
    fine_paid_method= Column(String,     nullable=True)          # upi | card | net | cash
    fine_paid_time  = Column(BigInteger, nullable=True)
    fine_time       = Column(BigInteger, nullable=True)
    auto_fine_applied= Column(Integer,   default=0)             # last auto-fine amount synced

    # Notification flags (prevent duplicate alerts)
    notified_warn       = Column(Boolean, default=False)        # 2h-before warning sent
    notified_overtime   = Column(Boolean, default=False)        # overtime-start alert sent

    user = relationship("User", back_populates="parking_sessions")


# ─────────────────────────────────────────────────────────────────────────────
# ParkingCounter  —  single-row table that drives PKG000001 IDs
# ─────────────────────────────────────────────────────────────────────────────
class ParkingCounter(Base):
    __tablename__ = "parking_counter"

    id      = Column(Integer, primary_key=True, default=1)
    counter = Column(Integer, default=1)
